const { commands } = require('./commands'); const { status } = require('../core/status'); const { getModules } = require('../core/moduleRegistry');
const { DependencyCheckerService } = require('../services/dependencyCheckerService'); const { DoctorService } = require('../services/doctorService'); const { SelfTestService } = require('../services/selfTestService'); const { FlatFileMemoryService } = require('../services/flatFileMemoryService'); const { CodeCacheService } = require('../services/codeCacheService'); const { RollingSummaryService } = require('../services/rollingSummaryService'); const { VaultIndexService } = require('../services/vaultIndexService'); const { MarkdownVaultService } = require('../services/markdownVaultService'); const { AuditLogService } = require('../services/auditLogService'); const { ZeroLeakSanitizerService } = require('../services/zeroLeakSanitizerService'); const { IntentRouterService } = require('../services/intentRouterService'); const { NasIndexerService } = require('../services/nasIndexerService'); const { MqttService } = require('../services/mqttService'); const { WakeOnLanService } = require('../services/wakeOnLanService'); const { ClamAvService } = require('../services/clamAvService'); const { DockerPlannerService } = require('../services/dockerPlannerService'); const { NodeRedConnectorService } = require('../services/nodeRedConnectorService'); const { ServerlessWebhookService } = require('../services/serverlessWebhookService'); const { SystemDiagnosticsService } = require('../services/systemDiagnosticsService'); const { AuditLogService: Audit } = require('../services/auditLogService');
class CommandRouter {
  constructor() { this.audit = new Audit(); }
  async handle(line) {
    const input = String(line || '').trim(); const [cmd, sub, ...rest] = input.split(' '); const text = rest.join(' '); let out;
    try {
      if (cmd === '/help') out = { commands }; else if (cmd === '/status') out = status(); else if (cmd === '/doctor') out = await new DoctorService().run(); else if (cmd === '/selftest') out = await new SelfTestService().run(); else if (cmd === '/deps') out = new DependencyCheckerService().checkAll();
      else if (cmd === '/memoria' && sub === 'prueba') out = new FlatFileMemoryService().add('memoria prueba'); else if (cmd === '/memoria' && sub === 'buscar') out = new FlatFileMemoryService().search(text);
      else if (cmd === '/codigo' && sub === 'prueba') out = new CodeCacheService().prueba(); else if (cmd === '/codigo' && sub === 'buscar') out = new CodeCacheService().buscar(text); else if (cmd === '/codigo' && sub === 'listar') out = new CodeCacheService().listar(); else if (cmd === '/codigo' && sub === 'estado') out = new CodeCacheService().estado();
      else if (cmd === '/summary' && sub === 'regenerar') out = new RollingSummaryService().regenerate(); else if (cmd === '/summary') out = new RollingSummaryService().read();
      else if (cmd === '/indexar') out = new VaultIndexService().index(); else if (cmd === '/indice' && sub === 'estado') out = new VaultIndexService().status();
      else if (cmd === '/vault' && sub === 'estado') out = new MarkdownVaultService().status(); else if (cmd === '/vault' && sub === 'crear') out = new MarkdownVaultService().createNote('bovedas', text || 'nueva-boveda', ''); else if (cmd === '/vault' && sub === 'listar') out = new MarkdownVaultService().list(); else if (cmd === '/vault' && sub === 'importar') out = { status: 'dry_run', dry_run: true, path: text }; else if (cmd === '/vault' && sub === 'verificar') out = new MarkdownVaultService().status();
      else if (cmd === '/auditoria' && sub === 'verificar') out = new AuditLogService().verify(); else if (cmd === '/auditoria') out = { file: require('../core/paths').paths.auditLog, verify: new AuditLogService().verify() };
      else if (cmd === '/modulos') out = getModules(); else if (cmd === '/zeroleak') out = new ZeroLeakSanitizerService().sanitize([sub, ...rest].join(' ')); else if (cmd === '/intencion') out = { intent: new IntentRouterService().classify([sub, ...rest].join(' ')) };
      else if (cmd === '/nas' && sub === 'estado') out = new NasIndexerService().status(); else if (cmd === '/nas' && sub === 'indexar') out = new NasIndexerService().index(); else if (cmd === '/nas' && sub === 'buscar') out = new NasIndexerService().search(text);
      else if (cmd === '/mqtt' && sub === 'estado') out = new MqttService().status(); else if (cmd === '/mqtt' && sub === 'publicar') out = await new MqttService().publish(rest.shift(), rest.join(' '));
      else if (cmd === '/wol' && sub === 'estado') out = new WakeOnLanService().status(); else if (cmd === '/wol' && sub === 'probar') out = { valid: new WakeOnLanService().isValidMac(text || rest[0] || '') }; else if (cmd === '/wol' && sub === 'enviar') out = await new WakeOnLanService().send(text || rest[0] || '');
      else if (cmd === '/clamav' && sub === 'estado') out = new ClamAvService().status(); else if (cmd === '/clamav' && sub === 'escanear') out = new ClamAvService().scan(text);
      else if (cmd === '/docker' && sub === 'estado') out = new DockerPlannerService().status(); else if (cmd === '/nodered' && sub === 'estado') out = new NodeRedConnectorService().status(); else if (cmd === '/nodered' && sub === 'ping') out = await new NodeRedConnectorService().ping(); else if (cmd === '/serverless' && sub === 'estado') out = new ServerlessWebhookService().status();
      else if (cmd === '/sistema' && sub === 'doctor') out = new SystemDiagnosticsService().diagnose(); else if (cmd === '/ntp' && sub === 'estado') out = { ntp: new SystemDiagnosticsService().diagnose().ntp }; else if (cmd === '/ip' && sub === 'estado') out = { ip_local: new SystemDiagnosticsService().ipLocal() }; else if (cmd === '/salir') out = { status: 'bye' }; else out = { status: 'unknown_command', help: '/help' };
      this.audit.record({ command: input, module: cmd.replace('/', '') || 'cli', result: 'ok', dry_run: true }); return out;
    } catch (error) { this.audit.record({ command: input, module: cmd.replace('/', '') || 'cli', result: `error:${error.message}`, dry_run: true }); return { status: 'error', message: error.message }; }
  }
}
module.exports = { CommandRouter };
