const assert = require('assert'); const path = require('path'); const fs = require('fs'); const os = require('os');
process.env.HANNA_DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'hanna-node-unit-'));
const { StartupService } = require('../src/services/startupService'); const { DependencyCheckerService } = require('../src/services/dependencyCheckerService'); const { SecretFilterService } = require('../src/services/secretFilterService'); const { PathGuardService } = require('../src/services/pathGuardService'); const { AuditLogService } = require('../src/services/auditLogService'); const { ZeroLeakSanitizerService } = require('../src/services/zeroLeakSanitizerService'); const { IntentRouterService } = require('../src/services/intentRouterService'); const { WakeOnLanService } = require('../src/services/wakeOnLanService'); const { VaultEncryptionService } = require('../src/services/vaultEncryptionService'); const { JsonlStoreService } = require('../src/services/jsonlStoreService'); const { ResponseFormatterService } = require('../src/services/responseFormatterService'); const { CommandRouter } = require('../src/cli/commandRouter'); const { TelegramBotIntegration } = require('../src/integrations/telegramBot'); const { NaturalCommandService } = require('../src/services/naturalCommandService'); const { AdminWebServer } = require('../src/integrations/adminWebServer'); const { WebChatServer } = require('../src/integrations/webChatServer'); const { MobileApiServer } = require('../src/integrations/mobileApiServer'); const { LlmRouterService } = require('../src/services/llmRouterService'); const { GroqAdapterService } = require('../src/services/groqAdapterService'); const { GeminiAdapterService } = require('../src/services/geminiAdapterService'); const { OpenRouterAdapterService } = require('../src/services/openRouterAdapterService'); const { OllamaAdapterService } = require('../src/services/ollamaAdapterService'); const { MqttService } = require('../src/services/mqttService'); const { SpotifyService } = require('../src/services/spotifyService'); const { ObsidianVaultService } = require('../src/services/obsidianVaultService'); const { EmotionStateService } = require('../src/services/emotionStateService'); const { WebCompactServer } = require('../src/integrations/webCompactServer'); const { HannaCore } = require('../src/core/hannaCore'); const { RbacService } = require('../src/services/rbacService'); const { TotpService } = require('../src/services/totpService'); const { paths } = require('../src/core/paths');

(async () => {
new StartupService().ensureDataLayout();
assert(new SecretFilterService().redact('api_key=abc token=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ').includes('[REDACTED]'));
const guard = new PathGuardService(); assert.strictEqual(guard.validate(path.join(paths.dataRoot, 'runtime', 'ok.txt')).ok, true); assert.strictEqual(guard.validate('../secret.txt').ok, false); assert.strictEqual(guard.validate(path.join(paths.dataRoot, '.env')).ok, false);
const auditFile = path.join(paths.logs, 'unit-audit.log'); const audit = new AuditLogService(auditFile); audit.record({ command: '/unit', module: 'test', result: 'ok', dry_run: true }); audit.record({ command: '/unit2', module: 'test', result: 'ok', dry_run: true }); assert.strictEqual(audit.verify().ok, true);
assert(new ZeroLeakSanitizerService().sanitize('email a@b.com ip 192.168.1.10 C:\\Users\\Eliezer token=abc').includes('[EMAIL]'));
assert.strictEqual(new IntentRouterService().classify('publicar en mqtt'), 'mqtt');
const wol = new WakeOnLanService(); assert.strictEqual(wol.isValidMac('00:11:22:33:44:55'), true); assert.strictEqual(wol.isValidMac('bad'), false);
const vault = new VaultEncryptionService(); const enc = vault.encryptText('hola', 'pass'); assert.strictEqual(vault.decryptText(enc, 'pass'), 'hola');
const store = new JsonlStoreService(path.join(paths.runtime, 'unit.jsonl')); store.append({ hello: 'world' }); assert.strictEqual(store.read(1)[0].hello, 'world');

const deps = new DependencyCheckerService();
const nodeDep = new DependencyCheckerService({ platform: process.platform, execPath: process.execPath }).checkOne('node'); assert.strictEqual(nodeDep.status, 'found'); assert.strictEqual(nodeDep.found, true); assert(nodeDep.path || nodeDep.version);
const npmDep = deps.checkOne('npm'); assert.notStrictEqual(npmDep.status, 'missing_dependency'); assert.strictEqual(npmDep.found, true); assert(npmDep.version);
const gitDep = deps.checkOne('git'); assert.notStrictEqual(gitDep.status, 'missing_dependency'); assert.strictEqual(gitDep.found, true); assert(gitDep.version.toLowerCase().includes('git'));
const winSystemctl = new DependencyCheckerService({ platform: 'win32', execPath: process.execPath }).checkOne('systemctl'); assert(['missing_dependency', 'not_applicable'].includes(winSystemctl.status)); assert.notStrictEqual(winSystemctl.status, 'failed');
const fakeWindowsSpawn = (command, args) => { const key = [command, ...(args || [])].join(' '); if (key === 'where.exe npm') return { status: 1, stdout: '', stderr: '' }; if (key === 'where.exe npm.cmd') return { status: 0, stdout: 'C:\\Program Files\\nodejs\\npm.cmd\r\n', stderr: '' }; if (key === 'where.exe git') return { status: 1, stdout: '', stderr: '' }; if (key === 'where.exe git.exe') return { status: 0, stdout: 'C:\\Program Files\\Git\\cmd\\git.exe\r\n', stderr: '' }; if (key.includes('node.exe --version')) return { status: 0, stdout: 'v24.16.0\n', stderr: '' }; if (key.includes('npm.cmd --version')) return { status: 0, stdout: '11.4.2\n', stderr: '' }; if (key.includes('git.exe --version')) return { status: 0, stdout: 'git version 2.45.0.windows.1\n', stderr: '' }; return { status: 1, stdout: '', stderr: '' }; };
const winDeps = new DependencyCheckerService({ platform: 'win32', execPath: 'C:\\Program Files\\nodejs\\node.exe', spawn: fakeWindowsSpawn });
assert.strictEqual(winDeps.checkOne('node').status, 'found'); assert.strictEqual(winDeps.checkOne('npm').status, 'found'); assert.strictEqual(winDeps.checkOne('git').status, 'found'); assert.strictEqual(winDeps.checkOne('timedatectl').status, 'not_applicable');

const router = new CommandRouter();
assert((await router.handle('/status')).includes('Hanna está activa'));
assert((await router.run('/status')).includes('Hanna está activa'));
const doctorOut = await router.run('/doctor'); assert(doctorOut.includes('Diagnóstico general')); assert(doctorOut.includes('Dependencias críticas'));
assert((await router.run('/deps')).includes('node'));
assert((await router.run('/auditoria verificar')).includes('Auditoría'));
assert(!(await router.run('hola')).includes('unknown_command'));
assert((await router.run('estado')).includes('Hanna está activa'));
assert((await router.run('diagnostico')).includes('Diagnóstico general'));
assert((await router.run('verifica auditoria')).includes('Auditoría'));
assert((await router.run('qué puedes hacer')).includes('Puedo ayudarte'));
const natural = new NaturalCommandService().normalize('  Qué   falta instalar?? '); assert.strictEqual(natural.matched, true); assert.strictEqual(natural.normalizedCommand, '/deps'); assert(natural.confidence > 0.5);
assert((await router.run('guarda esto en memoria: prueba')).includes('Guardé'));
assert((await router.run('busca en memoria prueba')).includes('memoria local'));
const qaOut = await router.run('busca que es un llm'); assert(qaOut.includes('motor IA') || qaOut.includes('Obsidian'));
assert((await router.run('qué es un llm')).includes('motor IA') || (await router.run('qué es un llm')).includes('Obsidian'));
assert((await router.run('explícame qué es un llm')).includes('motor IA') || (await router.run('explícame qué es un llm')).includes('Obsidian'));
assert((await router.run('guarda esto en obsidian: prueba :: contenido de prueba')).includes('Guardé la nota'));
assert((await router.run('busca en obsidian prueba')).includes('Obsidian'));
assert((await router.run('cómo te sientes')).includes('Estado emocional'));
assert((await router.run('estado emocional')).includes('Estado emocional'));
assert((await router.run('/obsidian estado')).includes('Obsidian/RAG activo'));
assert((await router.run('/ia estado')).includes('IA de Hanna'));
assert((await router.run('/telegram estado')).includes('Telegram'));
assert((await router.run('/web estado')).includes('Web compacta'));
assert.strictEqual(new ObsidianVaultService().status().status, 'ok');
assert.strictEqual(new EmotionStateService().getState().status, 'ok');
const formatter = new ResponseFormatterService();
assert(!formatter.format({ command: '/status', data: { runtime: 'node', dry_run: true, modules: 1 } }, { mode: 'human' }).trim().startsWith('{'));
assert(formatter.format({ ok: true }, { mode: 'json' }).trim().startsWith('{'));
assert((await router.run('/json /doctor')).trim().startsWith('{'));
let telegramCalled = false;
const noTokenTelegram = new TelegramBotIntegration({ dryRun: true, token: '' }); assert.strictEqual(noTokenTelegram.status().status, 'missing_configuration');
const telegram = new TelegramBotIntegration({ dryRun: true, token: 'fake-token', router: { run: async (text, context) => { telegramCalled = context.source === 'telegram' && text === 'hola'; return 'hola humano'; } } });
await telegram.handleMessage({ text: 'hola', chat: { id: 123 }, from: { id: 456, username: 'tester' } }); assert(telegramCalled);

assert.strictEqual((await new AdminWebServer({ router }).selfTest()).status, 'ok');
assert.strictEqual((await new WebChatServer({ router }).selfTest()).status, 'ok');
assert.strictEqual((await new MobileApiServer({ router }).selfTest()).status, 'ok');
assert.strictEqual((await new WebCompactServer({ router }).selfTest()).status, 'ok');
assert.strictEqual((await new HannaCore().start({ dryRun: true })).status, 'ok');
assert.strictEqual(new GroqAdapterService().status().status, 'missing_configuration');
assert.strictEqual(new GeminiAdapterService().status().status, 'missing_configuration');
assert.strictEqual(new OpenRouterAdapterService().status().status, 'missing_configuration');
assert.strictEqual(new OllamaAdapterService().status().status, 'missing_configuration');
assert.strictEqual((await new LlmRouterService().generate('hola')).status, 'missing_configuration');
assert.strictEqual(new MqttService().status().status, 'missing_configuration');
const spotify = new SpotifyService({ dryRun: true, clientId: '', clientSecret: '', redirectUri: '', refreshToken: '' }); assert.strictEqual(spotify.status().status, 'blocked_by_configuration'); assert.strictEqual((await spotify.pause()).status, 'blocked_by_configuration');
assert((await router.run('/spotify estado')).includes('Spotify está bloqueado'));
assert((await router.run('estado de spotify')).includes('Spotify está bloqueado'));
assert((await router.run('pausa spotify')).includes('Spotify está bloqueado'));
assert((await router.run('siguiente canción')).includes('Spotify está bloqueado'));
assert.strictEqual(new NaturalCommandService().normalize('pausa spotify').normalizedCommand, '/spotify pausar');
assert(['admin', 'root'].includes(new RbacService().active().role));
const totp = new TotpService(); const totpSecret = Buffer.from('12345678901234567890').toString('base64'); const code = totp.current(totpSecret).code; assert.strictEqual(totp.verify(code, totpSecret).valid, true);

const failingTelegram = new TelegramBotIntegration({ dryRun: true, token: 'fake-token', router: { run: async () => { throw new Error('stack should not leak'); } } }); const sent = await failingTelegram.sendMessage(1, await failingTelegram.router.run('x', { source: 'telegram' }).catch(() => 'Tuve un error interno procesando eso. Ya lo registré en auditoría. Prueba con ‘diagnóstico’ o ‘ayuda’.' )); assert(!sent.text.includes('stack should not leak'));
const telegramAudit = new AuditLogService().record({ source: 'telegram', userId: 1, username: 'u', chatId: 2, command: 'hola', originalInput: 'hola', normalizedCommand: 'hola', normalized_command: 'hola', module: 'telegram', result: 'ok', dry_run: true }); assert.strictEqual(telegramAudit.source, 'telegram'); assert.strictEqual(telegramAudit.chatId, 2);
console.log('PASS unit tests');
})().catch(error => { console.error(error); process.exit(1); });
